### ISSUE TITLE
Error produced when switching tabs in the demo

### ISSUE THREAD

**Issue by MichaelJBrune** [smix8/Godot_3D_Navigation_Jump_Links#2]
So in 3.4 at least, whenever you switch tabs with a JumpLinkNavigation node in it you get the following error:

 res://addons/navigation_jump_links/scripts/JumpLinkNavigation.gd:91 - Invalid call. Nonexistent function 'get_override_navmesh' in base 'Position3D (JumpLinkPosition.gd)

I suspect this is causing an additional issue where the scene becomes "[unsaved]" when loading up scenes with this node in it. It then prevents the system from loading up the project correctly.

I suspect this is due to circular references as this is what I've seen before with these issues.

**Comment by smix8** [comment]
Hello, I just tested with the official Godot 3.4 and the newest RC1 and don't get this error. Is it possible that one of the JumpLink Nodes in your scene was renamed or lost the attached script? That would explain the error msg because the links are collected by node name at scene start and if one node is renamed or without script it breaks. Cyclic ref errors in Godot usually print very different errors.

**Comment by MichaelJBrune** [comment]
Nope, nothing that I can see has changed from the repo. Simply downloading
the demo files and opening them with 3.4 creates the error on Windows 10
for me.

**Comment by MichaelJBrune** [comment]
to clarify now I am near a computer: https://github.com/smix8/Godot_3D_Navigation_Jump_Links/tree/godot_3.x_gdscript_demos is the branch I am downloading as a zip. Extracting it and opening with godot 3.4.0 without changes. I immediately get the issue. I can make a full video if you think that would be helpful.

**Comment by smix8** [comment]
Ahh I see now, this error msg is caused by the "tool" keyword that I had suppressed. Since Godot loads scenes differently in the editor all the required nodes are not ready when the "tool" script tries to collect them.

Tool was enabled so e.g. JumpLinkObject nodes add the required subnodes automatically while in the editor. As a workaround for now it is save to remove all the tool keywords in the scripts to removed the error msg with the drawback if you add new jumpnodes you have to place and name the required subnodes by hand without the tool keyword.

**Comment by smix8** [comment]
tool removed from demo projects with commit 6f8d5d020e5dd3424b1c53246fe838a92ea52f39
Will rework the pure addon branches differently to prevent this error spam.
